/**
 * SessionRepository — refresh-token rows + chain operations.
 *
 * Session lifecycle (Sprint 1 §9):
 *   - login → INSERT a session, chainId = its own id, parent = null.
 *   - refresh → in a tx:
 *       1. SELECT session by hash (FOR UPDATE)
 *       2. validate: not revoked, not expired
 *       3. INSERT new session: parent_session_id = old.id, chain_id = old.chainId
 *       4. UPDATE old: revoked_at = now, revoked_reason = 'rotated',
 *                     replaced_by_session_id = new.id
 *   - reuse detected → revoke entire chainId in one UPDATE.
 *   - logout → revoke single session.
 *   - logout-all → revoke every active session of the user.
 *
 * The unique index on `refresh_token_hash` doubles as a pessimistic lock
 * mechanism: only the first concurrent rotation will see the row in the
 * "active" state. The losing tx will read `revokedAt IS NOT NULL` and
 * trip the reuse-detection path.
 */
import { Injectable } from '@nestjs/common';
import { randomUUID } from 'node:crypto';

import { PrismaService } from '../../../infra/prisma';
import type { PrismaTx } from '../../../infra/prisma/types';

export type RevokedReason =
  | 'logout'
  | 'logout_all'
  | 'rotated'
  | 'reuse_detected'
  | 'admin'
  | 'password_changed';

export interface SessionRow {
  readonly id: string;
  readonly schoolId: string;
  readonly userId: string;
  readonly chainId: string;
  readonly parentSessionId: string | null;
  readonly replacedBySessionId: string | null;
  readonly issuedAt: Date;
  readonly expiresAt: Date;
  readonly revokedAt: Date | null;
  readonly revokedReason: string | null;
  readonly deviceId: string | null;
  readonly ip: string | null;
  readonly userAgent: string | null;
}

export interface CreateSessionInput {
  readonly schoolId: string;
  readonly userId: string;
  readonly refreshTokenHash: string;
  readonly expiresAt: Date;
  readonly chainId?: string;
  readonly parentSessionId?: string;
  readonly deviceId?: string;
  readonly ip?: string;
  readonly userAgent?: string;
}

@Injectable()
export class SessionRepository {
  constructor(private readonly prisma: PrismaService) {}

  // Cast through `unknown` to PrismaTx narrows the union out of the way of
  // TypeScript's recursion limit (the extended client + TX union becomes
  // too deep once the schema crosses ~40 models).
  private resolve(tx?: PrismaTx): PrismaTx {
    return tx ?? (this.prisma.client as unknown as PrismaTx);
  }

  /**
   * Create a brand-new session (login). When `chainId` is omitted we use
   * the row's own id — `id` is generated by Prisma's @default(uuid()), so
   * we mint it client-side via crypto.randomUUID and reuse it for both.
   */
  public async createForLogin(
    args: Omit<CreateSessionInput, 'chainId' | 'parentSessionId'>,
    tx?: PrismaTx,
  ): Promise<SessionRow> {
    const writer = this.resolve(tx);
    const id = randomUUID();
    const created = await writer.userSession.create({
      data: {
        id,
        schoolId: args.schoolId,
        userId: args.userId,
        refreshTokenHash: args.refreshTokenHash,
        expiresAt: args.expiresAt,
        chainId: id,
        deviceId: args.deviceId ?? null,
        ip: args.ip ?? null,
        userAgent: args.userAgent ?? null,
      },
    });
    return mapSession(created);
  }

  /** Create a rotated session that inherits the parent's chainId. */
  public async createForRotation(args: CreateSessionInput, tx?: PrismaTx): Promise<SessionRow> {
    if (args.chainId === undefined || args.parentSessionId === undefined) {
      throw new Error('createForRotation requires chainId and parentSessionId');
    }
    const writer = this.resolve(tx);
    const created = await writer.userSession.create({
      data: {
        schoolId: args.schoolId,
        userId: args.userId,
        refreshTokenHash: args.refreshTokenHash,
        expiresAt: args.expiresAt,
        chainId: args.chainId,
        parentSessionId: args.parentSessionId,
        deviceId: args.deviceId ?? null,
        ip: args.ip ?? null,
        userAgent: args.userAgent ?? null,
      },
    });
    return mapSession(created);
  }

  /** Look up a session by the SHA-256 of its refresh token. */
  public async findByTokenHash(tokenHash: string, tx?: PrismaTx): Promise<SessionRow | null> {
    const reader = this.resolve(tx);
    const row = await reader.userSession.findUnique({
      where: { refreshTokenHash: tokenHash },
    });
    return row === null ? null : mapSession(row);
  }

  /**
   * W1.4 — fetch the chain root for refresh-chain expiry preservation.
   *
   * The "root" is the session created at login: `parentSessionId IS NULL`
   * and `id === chainId`. Its `expiresAt` is the chain's original
   * deadline; rotations within the chain must never extend past it.
   *
   * Returns `null` if the chain has no live root row (shouldn't happen
   * outside data corruption — callers treat as a normal rotation
   * without a ceiling, which preserves legacy behaviour).
   */
  public async findChainRoot(chainId: string, tx?: PrismaTx): Promise<SessionRow | null> {
    const reader = this.resolve(tx);
    const row = await reader.userSession.findFirst({
      where: { chainId, parentSessionId: null },
    });
    return row === null ? null : mapSession(row);
  }

  /**
   * Cheap "is this session still alive?" check used by the JWT strategy
   * on every authenticated request. Returns true iff the row exists,
   * has `revokedAt IS NULL`, and has not yet expired.
   */
  public async isActiveById(args: { schoolId: string; sessionId: string }): Promise<boolean> {
    const reader = this.resolve();
    const row = await reader.userSession.findFirst({
      where: {
        schoolId: args.schoolId,
        id: args.sessionId,
        revokedAt: null,
        expiresAt: { gt: new Date() },
      },
      select: { id: true },
    });
    return row !== null;
  }

  /** Revoke a single session and link the replacement. Idempotent. */
  public async markRotated(args: {
    schoolId: string;
    sessionId: string;
    replacedBySessionId: string;
    at: Date;
  }, tx?: PrismaTx): Promise<void> {
    const writer = this.resolve(tx);
    await writer.userSession.update({
      where: { schoolId_id: { schoolId: args.schoolId, id: args.sessionId } },
      data: {
        revokedAt: args.at,
        revokedReason: 'rotated',
        replacedBySessionId: args.replacedBySessionId,
      },
    });
  }

  /** Revoke a single session (logout). Idempotent on already-revoked rows. */
  public async revokeOne(args: {
    schoolId: string;
    sessionId: string;
    reason: RevokedReason;
    at: Date;
  }, tx?: PrismaTx): Promise<void> {
    const writer = this.resolve(tx);
    await writer.userSession.updateMany({
      where: {
        schoolId: args.schoolId,
        id: args.sessionId,
        revokedAt: null,
      },
      data: { revokedAt: args.at, revokedReason: args.reason },
    });
  }

  /**
   * Revoke every (still-active) session sharing a chainId. Used by
   * reuse detection — the entire login chain dies on a single replay.
   */
  public async revokeChain(args: {
    chainId: string;
    reason: RevokedReason;
    at: Date;
  }, tx?: PrismaTx): Promise<number> {
    const writer = this.resolve(tx);
    const result = await writer.userSession.updateMany({
      where: { chainId: args.chainId, revokedAt: null },
      data: { revokedAt: args.at, revokedReason: args.reason },
    });
    return result.count;
  }

  /** Revoke every active session for a user (logout-all / password change). */
  public async revokeAllForUser(args: {
    schoolId: string;
    userId: string;
    reason: RevokedReason;
    at: Date;
  }, tx?: PrismaTx): Promise<number> {
    const writer = this.resolve(tx);
    const result = await writer.userSession.updateMany({
      where: {
        schoolId: args.schoolId,
        userId: args.userId,
        revokedAt: null,
      },
      data: { revokedAt: args.at, revokedReason: args.reason },
    });
    return result.count;
  }
}

function mapSession(row: {
  id: string;
  schoolId: string;
  userId: string;
  chainId: string;
  parentSessionId: string | null;
  replacedBySessionId: string | null;
  issuedAt: Date;
  expiresAt: Date;
  revokedAt: Date | null;
  revokedReason: string | null;
  deviceId: string | null;
  ip: string | null;
  userAgent: string | null;
}): SessionRow {
  return {
    id: row.id,
    schoolId: row.schoolId,
    userId: row.userId,
    chainId: row.chainId,
    parentSessionId: row.parentSessionId,
    replacedBySessionId: row.replacedBySessionId,
    issuedAt: row.issuedAt,
    expiresAt: row.expiresAt,
    revokedAt: row.revokedAt,
    revokedReason: row.revokedReason,
    deviceId: row.deviceId,
    ip: row.ip,
    userAgent: row.userAgent,
  };
}
